const bills=[['⚡','9月电费','陈序支付 · 4人均摊','¥328.60','待结算'],['🏠','10月房租','林默支付 · 4人均摊','¥7,200.00','已结清'],['◉','宽带年费','周屿支付 · 4人均摊','¥1,080.00','待结算'],['🔥','9月燃气费','许棠支付 · 4人均摊','¥86.40','已结清']];
const chores=[['今天','客厅日常清洁','扫地、整理茶几与沙发','许棠','完成'],['明天','厨房深度清洁','灶台、水槽与公共餐具','周屿','待完成'],['周五','卫生间清洁','台面、镜面与地面','陈序','待完成'],['周六','垃圾分类投放','清空所有垃圾桶','林默','待完成'],['周日','公共区域整理','玄关与阳台杂物归位','许棠','待完成']];
const supplies=[['🧻','卷纸','2 卷','15','low'],['🧴','洗洁精','约 150ml','20','low'],['🗑️','垃圾袋','18 个','65',''],['🧽','清洁海绵','3 块','75',''],['💧','饮用水','1 桶','30','low'],['🧺','洗衣液','约 1.2L','55','']];
const rules=[['01','夜间安静时段','工作日 23:00 后、周末 24:00 后降低音量。','已生效'],['02','公共区域使用后复位','厨房、客厅、卫生间使用后及时恢复整洁。','已生效'],['03','访客提前告知','留宿访客需至少提前一天在群内征得同意。','已生效'],['04','冰箱空间管理','食物标注姓名和日期，每周日共同清理过期食品。','已生效'],['05','调整夜间安静时段','提议周五、周六延后至 00:30。','3/4 已同意']];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function render(){
 $('#billList').innerHTML=bills.map((x,i)=>`<div class="bill-row"><span class="category">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><div><small>${i%2?'10月1日':'10月5日'} 记录</small></div><div class="amount"><b>${x[3]}</b><span class="status ${x[4]==='已结清'?'done':''}">${x[4]}</span></div></div>`).join('');
 $('#choreGrid').innerHTML=chores.map((x,i)=>`<article class="chore-card ${x[4]==='完成'?'completed':''}"><header><span class="tag">${x[0]}</span><span>${x[4]==='完成'?'✓':''}</span></header><h3>${x[1]}</h3><p>${x[2]}</p><footer><span class="avatar">${x[3][0]}</span><b>${x[3]}</b><button class="outline chore-action" data-i="${i}">${x[4]==='完成'?'已完成':'标记完成'}</button></footer></article>`).join('');
 $('#supplyGrid').innerHTML=supplies.map(x=>`<article class="supply-item"><div class="supply-top"><span>${x[0]}</span><span class="stock ${x[4]}">${x[4]?'库存偏低':'库存充足'}</span></div><h3>${x[1]}</h3><p>当前余量：${x[2]}</p><div class="meter"><i class="${x[4]}" style="width:${x[3]}%"></i></div><footer><span>上次由陈序补充</span><button class="outline add-shopping" data-name="${x[1]}">加入清单</button></footer></article>`).join('');
 $('#rulesList').innerHTML=rules.map((x,i)=>`<article class="rule-item"><span class="rule-number">${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div><div class="vote-box"><span>${x[3]}</span>${i===4?'<button class="primary agree">同意提案</button>':'<button class="outline">查看记录</button>'}</div></article>`).join('');
}
function switchView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});location.hash=id==='home'?'':id;}
$$('[data-view]').forEach(x=>x.onclick=()=>switchView(x.dataset.view));$$('[data-view-jump]').forEach(x=>x.onclick=()=>switchView(x.dataset.viewJump));
const modal=$('#modal');let modalType='bill';
function openModal(type){modalType=type;const names={bill:['NEW EXPENSE','记录一笔费用','例如：10月燃气费','输入金额，如 86.40'],supply:['NEW SUPPLY','登记公共物品','例如：抽纸','输入当前数量或提醒阈值'],rule:['NEW PROPOSAL','发起公约提案','例如：访客留宿约定','写下你的提议'],settle:['SETTLEMENT','确认本月结算','10月合租费用结算','本次应付 ¥286.40']};const n=names[type];$('#modalEyebrow').textContent=n[0];$('#modalTitle').textContent=n[1];$('#formName').placeholder=n[2];$('#formDetail').placeholder=n[3];modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(()=>$('#formName').focus(),100)}
$$('[data-open-modal]').forEach(x=>x.onclick=()=>openModal(x.dataset.openModal));$('.close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
$('#quickForm').onsubmit=e=>{e.preventDefault();const name=$('#formName').value,detail=$('#formDetail').value;if(modalType==='bill'){bills.unshift(['●',name,'林默支付 · 4人均摊',`¥${detail}`,'待结算']);render();switchView('bills')}else if(modalType==='supply'){supplies.unshift(['📦',name,detail,'50','']);render();switchView('supplies')}else if(modalType==='rule'){rules.push([String(rules.length+1).padStart(2,'0'),name,detail,'1/4 已同意']);render();switchView('rules')}modal.classList.remove('open');e.target.reset();toast(modalType==='settle'?'结算提醒已发送给室友':'已保存并同步给室友')};
document.addEventListener('click',e=>{const c=e.target.closest('.chore-action');if(c&&chores[c.dataset.i][4]!=='完成'){chores[c.dataset.i][4]='完成';render();toast('值日已完成，辛苦啦！')}const a=e.target.closest('.add-shopping,.mini-add');if(a){a.textContent='已加入 ✓';a.disabled=true;$('#shoppingCount').textContent=Number($('#shoppingCount').textContent)+1;toast(`${a.dataset.name||a.dataset.supply} 已加入采购清单`)}if(e.target.closest('.agree')){rules[4][3]='4/4 已同意';render();toast('全员通过，公约已生效')}});
$('#copyList').onclick=()=>{navigator.clipboard?.writeText('梧桐小屋采购清单：卷纸、洗洁精、饮用水');toast('采购清单已复制')};$('#swapBtn').onclick=()=>toast('换班请求已发给室友');
render();const initial=location.hash.slice(1);if(initial&&document.getElementById(initial))switchView(initial);
